# Generated by Django 4.1.7 on 2023-02-22 15:54

from django.core.management import call_command
from django.db import migrations


def fill_database_data(state, schema_editor):
    call_command('loaddata', 'data_fixture.json')


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0001_initial"),
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fill_database_data)
    ]
