# Generated by Django 4.1.5 on 2023-01-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_alter_employee_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name_plural": "dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
