# Generated by Django 4.1.5 on 2023-02-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_orderdish_alter_order_dishes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dishes",
            field=models.ManyToManyField(
                null=True,
                related_name="orders",
                through="cafe.OrderDish",
                to="cafe.dish",
            ),
        ),
        migrations.AlterField(
            model_name="orderdish",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderdish",
            name="dish",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_dish",
                to="cafe.dish",
            ),
        ),
    ]
