# Generated by Django 4.1.5 on 2023-02-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0003_alter_order_dishes_alter_orderdish_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="dishes",
            field=models.ManyToManyField(
                related_name="orders", through="cafe.OrderDish", to="cafe.dish"
            ),
        ),
    ]
